
line_length:
file_length : 700
warning: 120
error: 1200
ignores_function_declarations: true
ignores_comments: true
ignores_interpolated_strings: true
ignores_urls: true

disabled_rules:
  - line_length
  - function_body_length
  - type_body_length
  - identifier_name
  - enum_case_associated_values_counts
  - type_name
  - cyclomatic_complexity
  - force_cast
  - shorthand_operator
  - colon
  - opening_brace
  - return_arrow_whitespace
  - trailing_whitespace
  - syntactic_sugar
  - vertical_whitespace
  - statement_position
  - comma
  - control_statement
  - orphaned_doc_comment
  - trailing_newline
  - unused_optional_binding
  - leading_whitespace
  - trailing_semicolon
  - mark
